# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f514eedc591dfb47baf35f8a1dbb214608dfbcde3eea4d730ec3fa0c0ab488a896b65adff063a6f08dbaec89d5739e91c45c8587e9ecc88f28e9e16d4a96ba80

test:
  secret_key_base: 99c81b6a081f89c5a561dd4711335823f362c7e2a9e49bcc66e670f7b85889391cee1336a6284eb244d93125f0dbdb63fb508dee7b9d42ef18bd49ed70366c87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
